name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: toxdevorg
    name: tox-dev/azure-pipelines-template
    ref: master

trigger:
  batch: true
  branches:
    include:
    - master
    - rewrite
    - refs/tags/*
pr:
  branches:
    include:
    - master
    - rewrite

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_PROC_NR: '0'
  PRE_COMMIT_HOME: $(Pipeline.Workspace)/pre-commit-cache

jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: ''
    jobs:
      fix_lint:
        before:
        - task: CacheBeta@0
          displayName: cache pre-commit
          inputs:
            key: pre-commit | .pre-commit-config.yaml
            path: $(PRE_COMMIT_HOME)
      docs: null
      py38:
        image: [linux, windows, macOs]
      py27:
        image: [linux, windows, macOs]
      pypy:
        image: [linux]
      py37:
        image: [linux, windows, macOs]
      py36:
        image: [linux, windows, macOs]
      py35:
        image: [linux, windows, macOs]
      pypy3:
        image: [linux]
      dev: null
      package_description: null
    coverage:
      with_toxenv: 'coverage' # generate .tox/.coverage, .tox/coverage.xml after test run
      for_envs: [py38, py37, py36, py35, py27, pypy3, pypy]
    before:
      - task: UsePythonVersion@0
        condition: and(succeeded(), in(variables['TOXENV'], 'pypy'))
        displayName: provision pypy 3
        inputs:
          versionSpec: 'pypy3'
- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@tox
    parameters:
      external_feed: 'toxdev'
      pypi_remote: 'pypi-toxdev'
      dependsOn: [fix_lint, docs, package_description, dev, report_coverage]
